<?php

namespace App\Controller\Admin;

use App\Entity\User;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateField;
use EasyCorp\Bundle\EasyAdminBundle\Field\EmailField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class UserCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return User::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInSingular('auteur')
            ->setEntityLabelInPlural('auteurs')
            ->showEntityActionsInlined(); // TODO: Change the autogenerated stub
    }

    /*
    public function configureFields(string $pageName): iterable
    {
        return [

            TextField::new('pseudo'),
            EmailField::new('email'),
          DateField::new('registeredAt',"Date d'inscription")->hideOnForm(),
        ];
    }

*/
}
